# Generated by Django 3.1.12 on 2024-12-11 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未命名測驗', max_length=255)),
                ('user_id', models.CharField(max_length=100)),
                ('questions', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('backgroundImage', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('test_id', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('result_index', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TestResult',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('account', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
